{"name": "En el que valido la app con diferentes contraseñas y passwords -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Abro la app para poder iniciar sesion", "status": "passed", "start": 1715386267291, "stop": 1715386267292}, {"name": "When Inicio sesion con JOSY43 y Test4321", "status": "passed", "attachments": [{"name": "Evidence", "source": "5bf936f3-fa2e-40c3-99ca-3890cd9fbb27-attachment.png", "type": "image/png"}], "start": 1715386267293, "stop": 1715386273840}, {"name": "Then Valido que se abra el home de la app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "Algo salió mal", "source": "fc382323-5201-4bbe-a7e6-1d6fd445182a-attachment.png", "type": "image/png"}], "start": 1715386273840, "stop": 1715386282361}], "parameters": [{"name": "usuario", "value": "JOSY43"}, {"name": "password", "value": "Test4321"}], "start": 1715386262513, "stop": 1715386282363, "uuid": "7c856c11-65b5-4b5d-97e5-7e8ecf1eee04", "historyId": "2c87cd7e3936f1f9d55c428e8f13c70a", "fullName": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo: En el que valido la app con diferentes contraseñas y passwords", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}