{"name": "En el que valido la app con diferentes contraseñas y passwords -- @1.3 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Abro la app para poder iniciar sesion", "status": "passed", "start": 1715386287646, "stop": 1715386287646}, {"name": "When Inicio sesion con JOSY21 y Test2341", "status": "passed", "attachments": [{"name": "Evidence", "source": "a8a21733-22c1-4e26-9598-5d0fc4adb7a4-attachment.png", "type": "image/png"}], "start": 1715386287646, "stop": 1715386292648}, {"name": "Then Valido que se abra el home de la app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n", "trace": "  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "Algo salió mal", "source": "f4688517-b278-4030-b911-3b5bf88476c6-attachment.png", "type": "image/png"}], "start": 1715386292649, "stop": 1715386300708}], "parameters": [{"name": "usuario", "value": "JOSY21"}, {"name": "password", "value": "Test2341"}], "start": 1715386282370, "stop": 1715386300710, "uuid": "703720b5-b3eb-4f6a-a28c-3335efdf1fe4", "historyId": "a90a68048aade1e07b67697f222c5660", "fullName": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo: En el que valido la app con diferentes contraseñas y passwords", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}